name: Run Unit Tests

on: [push]

jobs: 
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v5 # baixa o codigo na maquina
      - uses: actions/setup-node@v6 # configura o node
        with:
          node-version: 22.9.0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
       

      # Agora este comando vai funcionar
      - name: Run pnpm ci
        run: pnpm ci

      - name: Run pnpm test
        run: pnpm test